#!/bin/ksh
#
#------------------------------------------------------------------------------
#--
#-- Copyright 2017 Tanel Poder ( tanel@tanelpoder.com | http://tanelpoder.com )
#--
#-- Licensed under the Apache License, Version 2.0 (the "License");
#-- you may not use this file except in compliance with the License.
#-- You may obtain a copy of the License at
#--
#--     http://www.apache.org/licenses/LICENSE-2.0
#--
#-- Unless required by applicable law or agreed to in writing, software
#-- distributed under the License is distributed on an "AS IS" BASIS,
#-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#-- See the License for the specific language governing permissions and
#-- limitations under the License.
#--
#------------------------------------------------------------------------------
#
# strip_stack by Tanel Poder (www.tanelpoder.com)
#
# strips program counter function offsets and aggregates dtrace stack sampler output
#
# usage: strip_stack <filename>
# 

cat $1 | sed 's/^ *//;s/+.*$//' | \
        awk '/^$/{ printf "\n" }/^[0-9]*$/{ printf ";%s", $1 }/[a-z]/{ printf "%s<-", $1 }END{ printf "\n" }' | \
        sort | \
	awk -F";" '
            /NR==1/{ sum=0; total=0; oldstack=$2 }
            { 
              if (oldstack==$2) {sum+=$3;total+=$3} 
              else {printf "%d %s\n", sum, oldstack; oldstack=$2; sum=$3} 
            }
            END {printf "%d %s\n%d total samples\n", sum, oldstack,total}
        ' | \
        sort -bnr 

