#!/bin/ksh

# "Quick Dtrace" script by Tanel Poder (http://www.tanelpoder.com)

#
# Copyright 2017 Tanel Poder ( tanel@tanelpoder.com | http://tanelpoder.com )
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PROCESS=$1
shift

for F in $* ; do

   FUNCLIST_ENTRY=${FUNCLIST_ENTRY}",pid\$target::$F:entry"
   FUNCLIST_RETURN=${FUNCLIST_RETURN}",pid\$target::$F:return"

done

FUNCLIST_ENTRY=`echo "$FUNCLIST_ENTRY" | sed 's/^,//'`
FUNCLIST_RETURN=`echo "$FUNCLIST_RETURN" | sed 's/^,//'`

echo $FUNCLIST_ENTRY
echo $FUNCLIST_RETURN

#dtrace -p $PROCESS -Fn $FUNCLIST"{ trace(probefunc); trace(arg0); trace(arg1); trace(arg2); trace(arg3); }"
#dtrace -p $PROCESS -Fn $FUNCLIST'{ printf("%16x %16x %16x %16x %16x %16x", arg0, arg1, arg2, arg3, arg4, arg5); }'
#dtrace -p $PROCESS -Fn $FUNCLIST'{ printf("%s %16x %16x %16x %16x %16x", copyinstr(arg0), arg1, arg2, arg3, arg4, arg5); }'

dtrace -Zp $PROCESS -Fn \
$FUNCLIST_ENTRY'{ printf("%16x ", arg0 ); }'\
$FUNCLIST_RETURN'{ printf("%16x", arg1); }'


